//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquilaErpWpfApp3.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SettingChnl {
            get {
                return ((string)(this["SettingChnl"]));
            }
            set {
                this["SettingChnl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SettingHttp {
            get {
                return ((string)(this["SettingHttp"]));
            }
            set {
                this["SettingHttp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SettingId {
            get {
                return ((string)(this["SettingId"]));
            }
            set {
                this["SettingId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SettingCompany {
            get {
                return ((string)(this["SettingCompany"]));
            }
            set {
                this["SettingCompany"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SettingLogImg {
            get {
                return ((string)(this["SettingLogImg"]));
            }
            set {
                this["SettingLogImg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SettingSignImg {
            get {
                return ((string)(this["SettingSignImg"]));
            }
            set {
                this["SettingSignImg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string str_PrnNm {
            get {
                return ((string)(this["str_PrnNm"]));
            }
            set {
                this["str_PrnNm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string str_weighing_Port_1 {
            get {
                return ((string)(this["str_weighing_Port_1"]));
            }
            set {
                this["str_weighing_Port_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string str_weighing_BaudRate_1 {
            get {
                return ((string)(this["str_weighing_BaudRate_1"]));
            }
            set {
                this["str_weighing_BaudRate_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string str_weighing_Parity_1 {
            get {
                return ((string)(this["str_weighing_Parity_1"]));
            }
            set {
                this["str_weighing_Parity_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string str_weighing_Length_1 {
            get {
                return ((string)(this["str_weighing_Length_1"]));
            }
            set {
                this["str_weighing_Length_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string str_weighing_StopBit_1 {
            get {
                return ((string)(this["str_weighing_StopBit_1"]));
            }
            set {
                this["str_weighing_StopBit_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string str_weighing_Type_1 {
            get {
                return ((string)(this["str_weighing_Type_1"]));
            }
            set {
                this["str_weighing_Type_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string str_email_id {
            get {
                return ((string)(this["str_email_id"]));
            }
            set {
                this["str_email_id"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string str_email_password {
            get {
                return ((string)(this["str_email_password"]));
            }
            set {
                this["str_email_password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string str_email_stmp {
            get {
                return ((string)(this["str_email_stmp"]));
            }
            set {
                this["str_email_stmp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string str_weighing_Port_2 {
            get {
                return ((string)(this["str_weighing_Port_2"]));
            }
            set {
                this["str_weighing_Port_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string str_weighing_BaudRate_2 {
            get {
                return ((string)(this["str_weighing_BaudRate_2"]));
            }
            set {
                this["str_weighing_BaudRate_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string str_weighing_Parity_2 {
            get {
                return ((string)(this["str_weighing_Parity_2"]));
            }
            set {
                this["str_weighing_Parity_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string str_weighing_Length_2 {
            get {
                return ((string)(this["str_weighing_Length_2"]));
            }
            set {
                this["str_weighing_Length_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string str_weighing_StopBit_2 {
            get {
                return ((string)(this["str_weighing_StopBit_2"]));
            }
            set {
                this["str_weighing_StopBit_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string str_weighing_Type_2 {
            get {
                return ((string)(this["str_weighing_Type_2"]));
            }
            set {
                this["str_weighing_Type_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_weighing_Checkd_2 {
            get {
                return ((bool)(this["is_weighing_Checkd_2"]));
            }
            set {
                this["is_weighing_Checkd_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\ADEM")]
        public string SettingAdemPath {
            get {
                return ((string)(this["SettingAdemPath"]));
            }
            set {
                this["SettingAdemPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\OPT")]
        public string SettingOptPath {
            get {
                return ((string)(this["SettingOptPath"]));
            }
            set {
                this["SettingOptPath"] = value;
            }
        }
    }
}
